### ISSUE TITLE
Could we add support for unsupported parts of Eigen (no pun intended)?

### ISSUE THREAD

**Issue by boris-kolpackov** [build2-packaging/Eigen#2]
From the slack channel:

> Good Evening, thanks so much for everyone's hard work.
>
> Are there any plans to include the "unsupported" features from the Eigen Library in the build2's cppget's package? I found myself needing Eigen's tensor functionality that's located in `unsupported/Eigen/CXX11/Tensor`. I was able to copy the `unsupported` folder from https://gitlab.com/libeigen/eigen/-/tree/3.4/ into the extracted `eigen 3.4` build2 package folder. That let me use eigen's unsupported tensors... So I'm hoping that including eigen's "unsupported" features will be as simple as copying the unsupported folder to the correct location.
>
> I'm willing to work on this one, please let me know if/how I can contribute. Thanks!

It feels like this should be pretty straightforward to support as an optional feature with a configuration variable (e.g., `config.Eigen.unsupported ?= false`). I looked around in upstream and it seems everything under `unsupported/` is still header-only. So all we will need to do when this feature is enabled is to list all the headers in `unsupported/Eigen/` as prerequisites and add `-I` pointing to `unsupported/`. Installation will be slightly trickier: we probably don't want to install it as `/usr/include/unsupported/Eigen/` but we could do `/usr/include/Eigen/unsupported/Eigen/` and then add `/usr/include/Eigen/unsupported/` to pkg-config files (`cxx.pkgconfig.include`).

Thoughts?

**Comment by lyrahgames** [comment]
This sounds very reasonable to me. I will have time to look into this in two or three weeks, I think. If it would need to be done earlier someone else should try to update the package for now.

**Comment by lyrahgames** [comment]
The unsupported modules of Eigen can now be enabled by setting the config variable `config.Eigen.unsupported` to true.
My local tests succeeded. If you have time to look over it, it would be nice. In the case, you are ok with the implementation, I would publish a new package version.
How can I use `bdep ci` with different configurations at once?

**Comment by boris-kolpackov** [comment]
> If you have time to look over it, it would be nice.

Looks good to me.

> How can I use `bdep ci` with different configurations at once?

This feature is available in 0.16.0: https://build2.org/stage/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-build-config

In this case, you could just add a package configuration for `unsupported`, something like this:

```
unsupported-build-config: config.Eigen.unsupported=true
```

In the meantime (until 0.16.0 is release) if you have the staged toolchain, you can test this manually:

```
bdep ci --server https://ci.stage.build2.org --override 'unsupported-build-config: config.Eigen.unsupported=true' --package-config unsupported
```

For details, see: https://build2.org/stage/bdep/doc/bdep-ci.xhtml

**Comment by lyrahgames** [comment]
> Looks good to me.

Perfect, thank you. Needed to change a little bit due to some issues that came up when testing the installed version. But I have finally published the new package. I will close this issue for now.

> > How can I use `bdep ci` with different configurations at once?
> 
> This feature is available in 0.16.0: https://build2.org/stage/bpkg/doc/build2-package-manager-manual.xhtml#manifest-package-build-config
> 
> In this case, you could just add a package configuration for `unsupported`, something like this:
> 
> ```
> unsupported-build-config: config.Eigen.unsupported=true
> ```
> 
> In the meantime (until 0.16.0 is release) if you have the staged toolchain, you can test this manually:
> 
> ```
> bdep ci --server https://ci.stage.build2.org --override 'unsupported-build-config: config.Eigen.unsupported=true' --package-config unsupported
> ```
> 
> For details, see: https://build2.org/stage/bdep/doc/bdep-ci.xhtml

Thank you! This has been very useful.

**Comment by boris-kolpackov** [comment]
The `test-installed` step is still failing in the submitted revision: https://queue.cppget.org/Eigen/3.4.0+2

I believe the reason is that the `tests` subproject does not have the `config.Eigen.unsupported` value, which is necessary when this subproject is configured separately (as is the case during the `test-installed` step). This is a bit of a nuance that I didn't spot during my review. The correct way to fix this is for the library to export this value via metadata and for the tests (and potentially other applications) to use that to make decisions. The mechanism is describe here: https://github.com/build2/HOWTO/blob/master/entries/convey-additional-information-with-exe-lib.md

**Comment by lyrahgames** [comment]
> The `test-installed` step is still failing in the submitted revision: https://queue.cppget.org/Eigen/3.4.0+2

Oh, yes. Over the course of testing the version that enables the unsupported modules, I totally forgot to test the case with unsupported modules disabled.

> I believe the reason is that the `tests` subproject does not have the `config.Eigen.unsupported` value, which is necessary when this subproject is configured separately (as is the case during the `test-installed` step). This is a bit of a nuance that I didn't spot during my review. The correct way to fix this is for the library to export this value via metadata and for the tests (and potentially other applications) to use that to make decisions. The mechanism is describe here: https://github.com/build2/HOWTO/blob/master/entries/convey-additional-information-with-exe-lib.md

You are right and I already did a similar thing for another library package.
I have now added the metadata to the library and ran some CI tests with both configs.
- https://ci.stage.build2.org/@23da340d-cb4d-4105-8474-bb870e1a1380
- https://ci.stage.build2.org/@04e5ffb7-cf96-42f9-bc91-94d3ffe48de1

Right now, it looks to me, like it would work.
If you would also say it is ok, I will try to publish the package version again.

**Comment by boris-kolpackov** [comment]
Looks good to me, thanks!

**Comment by lyrahgames** [comment]
Nice! Could you remove the old package `v3.4.0+2` from the queue? Otherwise, I cannot publish the new package. Or should I create a new package version `v3.4.0+3` for that?

**Comment by boris-kolpackov** [comment]
Yes, the correct way is to make a new revision (generally, you don't want the same version to mean different things, if at all possible, and here it's quite easy to avoid that).

**Comment by lyrahgames** [comment]
Thanks for the help. Published the new revision. Hopefully everything will work now.

**Comment by boris-kolpackov** [comment]
Yes, looks good now, published. Thanks for your work on this!

**Comment by michaelijah** [comment]
Hi thanks to both of you for your work on this, I just ran a bpkg build eigen. It updated and eigen::tensors worked just fine with no alterations to my code. Regards
